[project]
name = "chatbot-ui"
version = "0.1.0"
description = "GUI for interacting with the agent."
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["flask>=3.1.1", "requests>=2.32.4"]

[tool.ruff.format]
quote-style = "single"
