[project]
name = "frontend"
version = "0.1.0"
description = "frontend streamlit project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "plotly>=6.3.0",
    "requests>=2.32.5",
    "streamlit>=1.50.0",
]

[tool.ruff.format]
quote-style = "single"
