services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    env_file:
      - .env
    ports:
      - 8501:8501
    networks:
      - mainnet

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - mainnet

networks:
  mainnet:
    driver: bridge
