services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501
    networks:
      - mainnet

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - mainnet

  mysql:
    image: mysql
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-init.db/init.sql
    ports:
      - 3306:3306
    networks:
      - mainnet

networks:
  mainnet:
    driver: bridge
