services:
  
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501
    networks:
      - mainnet
      
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - mainnet
    restart: always

  mysql:
    image: mysql
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - mainnet
    restart: always

networks:
  mainnet:
    driver: bridge
volumes:
  data:
