from langchain.tools import tool

from src.agents.data_analyst_agent import DataAnalystAgent


@tool('DataAnalyst')
def use_data_analyst(user_request: str):
    """This tool calls the Data Analyst to work on user's requests received. The data and insights generated by the agent are returned. Before using, check if the request is for a graph or is ambiguous or requires specifying columns, then ask the user to be more specific."""
    data_analyst = DataAnalystAgent()

    response = data_analyst.run(user_request)

    return {'results': response['output']}
